name: Tests
on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * 6'

jobs:
  tests:
    name: Test ${{ matrix.swoole-version }} against php ${{ matrix.php-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        php-version: [ '8.2', '8.3' ]
        swoole-version:
          - swoole-5.1.6
          - swoole-6.0.0
          - openswoole-22.1.2
          - openswoole-25.2.0
        include:
          - os: ubuntu-latest
            php-version: '8.4'
            swoole-version: swoole-6.0.0
          - os: ubuntu-latest
            php-version: '8.4'
            swoole-version: openswoole-25.2.0
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Setup PHP environment
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: pecl, composer, phpunit, blackfire
          extensions: ${{ matrix.swoole-version }}, blackfire
          coverage: none
        env:
          fail-fast: true
          BLACKFIRE_SERVER_ID: ${{ secrets.BLACKFIRE_SERVER_ID }}
          BLACKFIRE_SERVER_TOKEN: ${{ secrets.BLACKFIRE_SERVER_TOKEN }}
          BLACKFIRE_CLIENT_ID: ${{ secrets.BLACKFIRE_CLIENT_ID }}
          BLACKFIRE_CLIENT_TOKEN: ${{ secrets.BLACKFIRE_CLIENT_TOKEN }}
      - name: Verify PHP environment
        run: |
          php --ri swoole || php --ri openswoole
          php --ri blackfire
      - name: Install dependencies
        run: composer install -n
      - name: Run test suite
        run: vendor/bin/phpunit
